// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bWzKwhiAd0xYFBV9QEUwfvQs87TJBWU',
    appId: '1:656676613197:web:263db6437d7758b9518004',
    messagingSenderId: '656676613197',
    projectId: 'triviai-22615',
    authDomain: 'triviai-22615.firebaseapp.com',
    storageBucket: 'triviai-22615.firebasestorage.app',
    measurementId: 'G-Y5GE3HZETM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApjgFNSVGrlrd486Z0Cqo_oM8t2zP5QVE',
    appId: '1:656676613197:android:5b9bfe91eb53ab79518004',
    messagingSenderId: '656676613197',
    projectId: 'triviai-22615',
    storageBucket: 'triviai-22615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNz5p0f_v3uGAVHXxyXlpxeV6s7b6iMLY',
    appId: '1:656676613197:ios:643f9e0ae53fd8f6518004',
    messagingSenderId: '656676613197',
    projectId: 'triviai-22615',
    storageBucket: 'triviai-22615.firebasestorage.app',
    iosBundleId: 'com.example.triviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNz5p0f_v3uGAVHXxyXlpxeV6s7b6iMLY',
    appId: '1:656676613197:ios:643f9e0ae53fd8f6518004',
    messagingSenderId: '656676613197',
    projectId: 'triviai-22615',
    storageBucket: 'triviai-22615.firebasestorage.app',
    iosBundleId: 'com.example.triviApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_bWzKwhiAd0xYFBV9QEUwfvQs87TJBWU',
    appId: '1:656676613197:web:49ac7448b2bd36fa518004',
    messagingSenderId: '656676613197',
    projectId: 'triviai-22615',
    authDomain: 'triviai-22615.firebaseapp.com',
    storageBucket: 'triviai-22615.firebasestorage.app',
    measurementId: 'G-MMTH6BBNLS',
  );
}
